sonar.projectKey=mobead-lucas-alves
sonar.projectName=MobEAD - Lucas Alves
sonar.projectVersion=1.0

sonar.sources=Scripts,lib,index.html
sonar.tests=tests
sonar.exclusions=**/Kickstrap/**,**/*.css,**/*.less,**/__MACOSX/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

# Host e token são passados via Jenkins (withSonarQubeEnv)
# Para execução manual local:
# sonar.host.url=http://localhost:9000
# sonar.token=SEU_TOKEN_AQUI
